<?php
/**
 * @var Macopedia_EasyMenu_Block_Tree $this
 */
if(Mage::helper('EasyMenu')->isEnabled()): ?>
    <nav id="nav">
		<ul class="nav-primary">
        <?php
        /**
         * @var $cat array
         */
        foreach($this->getRootCategories() as $cat){
            echo $this->renderCategory($cat, false);
        }
        ?>
        </ul>
    </nav>
<?php endif; ?>
